language: go

go:
  - master

install:
  - go get -u -v github.com/spf13/hugo

script:
  - hugo
deploy:
  local_dir: public 
  repo: conarocks/conarocks.github.io 
  target_branch: master 
  provider: pages
  skip_cleanup: true
  github_token: $GITHUB_TOKEN 
  email: geral@cona.rocks
  name: "Cona Rocks"
  on:
    branch: master
